### ISSUE TITLE
Integrate NCDOT TIMS data

### ISSUE THREAD

**Issue by jtbry** [jtbry/CharlotteRoadReports#1]
May be worth collecting data from NCDOT's TIMS system. This API shows road closures, construction, weather and possibly some other stuff. Could be worth integrating this in polling alongside CMPD data but it is more planned obstructions rather than spontaneous incidents.

https://tims.ncdot.gov/TIMS/WebService/WebServiceDescription.aspx

TIMS can also provide cameras and images from said cameras, for example a request to the url `https://tims.ncdot.gov/tims/api/traffic/cameras/289` will provide information about the camera and a url to an image from it. This could definitely be worth integrating, could possibly get pictures / footage on incidents in progress reported by CMPD

There is an existing NC Government website that uses / displays some of this information that can be used for reference https://drivenc.gov/

**Comment by jtbry** [comment]
If polling this data is to be implemented it may be worth remaking the incident model. Currently the incident model basically conforms to the JSON Schema provided by CMPD API. Instead, the struct used to unmarshal JSON should be defined in the package where polling is done (main package for now)

This way each polling service can create an incident object out of data that doesn't fit the same schema as CMPD data. Adding this will make it easier to integrate new event/incident types from different sources in the future.

Only downside to doing this is that the database will likely have to be reset to accomodate appropriate changes to the incident model, could possibly make a script that will convert existing data to match new model. Could possibly done through a [GORM Migration.](https://gorm.io/docs/migration.html)

**Comment by ihatedwang** [comment]
I agree, this is certainly something we need to look into.

**Comment by jtbry** [comment]
After a second look, the TIMS API does not provide many incidents and the few it does provide don't really fit for this application. They are mainly pre-planned road closures or construction events so it wouldn't be worth the effort to display them properly with CMPD incidents.

As well the showing the cameras is also not worth the effort. Most of the cameras are only on the highways, not near where accidents are reported, and the cameras also do not provide live stream so they may not be good for real time data. Also, adding the cameras to the active map clutters it immensely and is not worth the distraction from actual active incidents.
